# 默认使用同目录下的 .env 文件作为 环境变量 配置文件，可以通过 shell> docker-compose --env-file /path 来自定义环境变量配置文件
version: "3.8"    # 表示当前 docker-compose(Compose specification) 的版本，版本 "3.8"  需要 docker 的版本为 19.03.0+

# 扩展字段 YAML Anchor: key 必须是 "x-" 开头
x-redis-img: &x-redis-img redis:7.2.4-bookworm              # redis 7.4 版本开始，开源协议变更，慎用

services:
  redis-standalone:
    image: *x-redis-img
    ports: [ 6379:6379 ]
    volumes:
      - ./redis/standalone/redis.conf:/etc/redis/redis.conf:ro
      - ${BASE_PATH:-.}/redis/standalone/data:/data:rw
    command: [ redis-server, /etc/redis/redis.conf ]
    #entrypoint: [ sleep, 1d, 2h, 3m, 4s ]
    #command: [ ]
    container_name: redis
